import type { HouseholdApp } from '../apps';

/** An app's family logo. The markup is trusted: generated by the kit's logoSvg from a fixed glyph. */
export function AppIcon({ app, size }: { app: HouseholdApp; size: number }) {
  return (
    <span
      aria-hidden="true"
      className="inline-flex shrink-0 [&>svg]:h-full [&>svg]:w-full"
      style={{ width: size, height: size }}
      dangerouslySetInnerHTML={{ __html: app.icon }}
    />
  );
}
