import { registerSW } from 'virtual:pwa-register';
import { APPS } from './apps';
import '@huishouden/pwa-kit/theme.css';
import './style.css';
import { mountHouseholdPanel } from './household-panel';
import { mountAppBar } from './app-bar';

registerSW({ immediate: true });

function greeting(hour: number): string {
  if (hour < 12) return 'Goedemorgen';
  if (hour < 18) return 'Goedemiddag';
  return 'Goedenavond';
}

document.getElementById('greeting')!.textContent = greeting(new Date().getHours());

const nav = document.getElementById('apps')!;
for (const app of APPS) {
  const tile = document.createElement('a');
  tile.className = 'tile';
  tile.href = app.url;

  const icon = document.createElement('span');
  icon.className = 'tile__icon';
  icon.setAttribute('aria-hidden', 'true');
  icon.innerHTML = app.icon; // trusted: generated by the kit's logoSvg from a fixed glyph

  const name = document.createElement('span');
  name.className = 'tile__name';
  name.textContent = app.name;

  const desc = document.createElement('span');
  desc.className = 'tile__desc';
  desc.textContent = app.description;

  tile.append(icon, name, desc);
  nav.append(tile);
}

mountHouseholdPanel(document.getElementById('household')!);
mountAppBar(document.querySelector('hh-app-bar')!);
