import { registerSW } from 'virtual:pwa-register';
import { APPS } from './apps';
import '@huishouden/pwa-kit/theme.css';
import './style.css';
import './dutch-word';
import './household-view';
import { mountHouseholdPanel } from './household-panel';
import { mountAppBar } from './app-bar';

registerSW({ immediate: true });

/** The greeting is Dutch; each word explains itself on hover or tap (src/dutch-word.ts). */
const GREETINGS = [
  { until: 12, word: 'Goedemorgen', say: 'KHOO-duh-mor-khun', means: 'Good morning' },
  { until: 18, word: 'Goedemiddag', say: 'KHOO-duh-mid-dahkh', means: 'Good afternoon' },
  { until: 24, word: 'Goedenavond', say: 'KHOO-duh-nah-vont', means: 'Good evening' },
];

function renderGreeting(hour: number) {
  const g = GREETINGS.find((x) => hour < x.until)!;
  const el = document.createElement('hh-word');
  el.setAttribute('say', g.say);
  el.setAttribute('means', g.means);
  el.textContent = g.word;
  document.getElementById('greeting')!.replaceChildren(el);
}

renderGreeting(new Date().getHours());

const nav = document.getElementById('apps')!;
for (const app of APPS) {
  const tile = document.createElement('a');
  tile.className = 'tile';
  tile.href = app.url;

  const icon = document.createElement('span');
  icon.className = 'tile__icon';
  icon.setAttribute('aria-hidden', 'true');
  icon.innerHTML = app.icon; // trusted: generated by the kit's logoSvg from a fixed glyph

  const name = document.createElement('span');
  name.className = 'tile__name';
  name.textContent = app.name;

  const desc = document.createElement('span');
  desc.className = 'tile__desc';
  desc.textContent = app.description;

  tile.append(icon, name, desc);
  nav.append(tile);
}

mountHouseholdPanel(document.querySelector('hh-household')!);
mountAppBar(document.querySelector('hh-app-bar')!);
