import { arrangeTiles, layoutOf, sameLayout, type HouseholdApp, type PortalLayout } from './apps';

/** Everything the tiles show. `src/tiles-panel.ts` derives it from the registry and the household's layout. */
export interface TilesView {
  /** Every app with a tile, in registry order. */
  apps: HouseholdApp[];
  /** The household's saved layout; the registry's order when there is none. */
  layout?: PortalLayout;
  /** A signed-in member of a household, who may arrange its tiles. */
  canArrange?: boolean;
}

export interface LayoutSave {
  layout: PortalLayout;
  /** What it replaces, for Undo. */
  previous: PortalLayout;
}

interface Toast {
  text: string;
  kind: 'notice' | 'error';
  undo?: PortalLayout;
}

const esc = (s: string) => s.replace(/[&<>"']/g, (c) => `&#${c.charCodeAt(0)};`);

const ARROW = '<svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M19 12H5"/><path d="m12 19-7-7 7-7"/></svg>';

/**
 * `<hh-tiles>`: the app tiles, the household's hidden apps under "More apps", and arranging them.
 * It holds no data and talks to nothing: set `view`, and it reports a new layout as an
 * `hh-layout-save` event (`detail` is a `LayoutSave`). Done saves; Undo saves the previous layout.
 * The screenshot tests set `view` directly to show a household's layout without signing in.
 */
export class HhTiles extends HTMLElement {
  #view: TilesView = { apps: [] };
  #arranging = false;
  #draft: HouseholdApp[] = [];
  #draftHidden = new Set<string>();
  #moreOpen = false;
  #toast: Toast | undefined;
  #toastTimer: ReturnType<typeof setTimeout> | undefined;
  #announce = '';
  #dragging: string | undefined;

  get view() {
    return this.#view;
  }

  set view(next: TilesView) {
    this.#view = next;
    if (!next.canArrange) this.#arranging = false;
    this.#render();
  }

  connectedCallback() {
    this.#render();
  }

  /** Shows a short message at the bottom of the screen, with Undo when `undo` is given. */
  toast(text: string, kind: Toast['kind'] = 'notice', undo?: PortalLayout) {
    clearTimeout(this.#toastTimer);
    this.#toast = { text, kind, undo };
    this.#toastTimer = setTimeout(() => {
      this.#toast = undefined;
      this.#render();
    }, kind === 'error' ? 9000 : 6000);
    this.#render();
  }

  #arranged() {
    return arrangeTiles(this.#view.apps, this.#view.layout);
  }

  #current(): PortalLayout {
    const { all, more } = this.#arranged();
    return layoutOf(all, more.map((a) => a.repo));
  }

  #emitSave(layout: PortalLayout, previous: PortalLayout) {
    this.dispatchEvent(new CustomEvent<LayoutSave>('hh-layout-save', { detail: { layout, previous }, bubbles: true }));
  }

  /** Re-renders, keeping focus on the same control. */
  #render(focus?: string) {
    const active = this.contains(document.activeElement) ? (document.activeElement as HTMLElement).dataset.key : undefined;
    this.innerHTML = this.#arranging ? this.#arrangeHtml() : this.#tilesHtml();
    this.insertAdjacentHTML('beforeend', this.#toastHtml());
    this.#bind();
    const key = focus ?? active;
    if (key) this.querySelector<HTMLElement>(`[data-key="${key}"]`)?.focus();
  }

  #tile(app: HouseholdApp, extra = '') {
    // The icon is trusted: generated by the kit's logoSvg from a fixed glyph.
    return `<a class="tile${extra}" href="${esc(app.url)}">
      <span class="tile__icon" aria-hidden="true">${app.icon}</span>
      <span class="tile__name">${esc(app.name)}</span>
      <span class="tile__desc">${esc(app.description)}</span>
    </a>`;
  }

  #tilesHtml(): string {
    const { shown, more } = this.#arranged();
    const tiles = `<nav class="tiles" aria-label="Household apps">${shown.map((a) => this.#tile(a)).join('')}</nav>`;
    const moreRow = more.length
      ? `<details class="more-apps"${this.#moreOpen ? ' open' : ''}>
          <summary data-key="more">More apps <span class="muted">(${more.length})</span></summary>
          <nav class="more-apps__list" aria-label="More apps">${more.map((a) => this.#tile(a, ' tile--small')).join('')}</nav>
        </details>`
      : '';
    const arrange = this.#view.canArrange ? `<button class="link tiles-foot__arrange" data-key="arrange">Arrange</button>` : '';
    return tiles + (moreRow || arrange ? `<div class="tiles-foot">${moreRow}${arrange}</div>` : '');
  }

  #arrangeHtml(): string {
    const last = this.#draft.length - 1;
    const tiles = this.#draft
      .map((app, i) => {
        const hidden = this.#draftHidden.has(app.repo);
        const name = esc(app.name);
        return `<li class="tile tile--arrange${hidden ? ' tile--hidden' : ''}" data-repo="${esc(app.repo)}"${this.#dragging === app.repo ? ' data-dragging' : ''}>
          <span class="tile__icon" aria-hidden="true">${app.icon}</span>
          <span class="tile__name">${name}${hidden ? ' <span class="badge badge--hidden">Hidden</span>' : ''}</span>
          <span class="tile__desc">${hidden ? 'Under More apps' : esc(app.description)}</span>
          <span class="tile__controls">
            <button class="tile__move" data-key="up:${esc(app.repo)}" aria-label="Move ${name} earlier" title="Move earlier"${i === 0 ? ' disabled' : ''}>${ARROW}</button>
            <button class="tile__move tile__move--later" data-key="down:${esc(app.repo)}" aria-label="Move ${name} later" title="Move later"${i === last ? ' disabled' : ''}>${ARROW}</button>
            <button class="hh-button hh-button--quiet tile__toggle" data-key="toggle:${esc(app.repo)}" aria-label="${hidden ? 'Show' : 'Hide'} ${name}">${hidden ? 'Show' : 'Hide'}</button>
          </span>
        </li>`;
      })
      .join('');
    return `
      <div class="arrange-bar">
        <div>
          <h2 class="arrange-bar__title" tabindex="-1" data-key="title">Arrange apps</h2>
          <p class="muted small">Move apps, or hide the ones your household doesn't use. Everyone in the household sees this layout.</p>
        </div>
        <div class="arrange-bar__actions">
          <button class="hh-button hh-button--quiet" data-key="cancel">Cancel</button>
          <button class="hh-button" data-key="done">Done</button>
        </div>
      </div>
      <ol class="tiles tiles--arranging" aria-label="Household apps, in order">${tiles}</ol>
      <p class="visually-hidden" role="status">${esc(this.#announce)}</p>`;
  }

  #toastHtml(): string {
    const t = this.#toast;
    if (!t) return '';
    return `<div class="toast${t.kind === 'error' ? ' toast--error' : ''}" role="${t.kind === 'error' ? 'alert' : 'status'}">
      <span>${esc(t.text)}</span>
      ${t.undo ? '<button class="toast__undo" data-key="undo">Undo</button>' : ''}
    </div>`;
  }

  #startArranging() {
    const { all, more } = this.#arranged();
    this.#draft = all;
    this.#draftHidden = new Set(more.map((a) => a.repo));
    this.#announce = '';
    this.#arranging = true;
    this.#render('title');
  }

  #stopArranging(save: boolean) {
    const previous = this.#current();
    const next = layoutOf(this.#draft, this.#draftHidden);
    this.#arranging = false;
    if (save && !sameLayout(previous, next)) {
      this.#emitSave(next, previous);
      this.toast('Saved for everyone in the household.', 'notice', previous);
    }
    this.#render('arrange');
  }

  #move(repo: string, to: number) {
    const from = this.#draft.findIndex((a) => a.repo === repo);
    if (from < 0 || to < 0 || to >= this.#draft.length || from === to) return;
    const [app] = this.#draft.splice(from, 1);
    this.#draft.splice(to, 0, app);
    this.#announce = `${app.name} moved to ${to + 1} of ${this.#draft.length}.`;
  }

  #bind() {
    const on = (selector: string, type: string, handler: (e: Event) => void) =>
      this.querySelectorAll(selector).forEach((el) => el.addEventListener(type, handler));

    on('[data-key="arrange"]', 'click', () => this.#startArranging());
    on('.more-apps', 'toggle', (e) => (this.#moreOpen = (e.currentTarget as HTMLDetailsElement).open));
    on('[data-key="cancel"]', 'click', () => this.#stopArranging(false));
    on('[data-key="done"]', 'click', () => this.#stopArranging(true));
    on('.arrange-bar, .tiles--arranging', 'keydown', (e) => {
      if ((e as KeyboardEvent).key === 'Escape') this.#stopArranging(false);
    });
    on('[data-key="undo"]', 'click', () => {
      const undo = this.#toast?.undo;
      clearTimeout(this.#toastTimer);
      this.#toast = undefined;
      if (undo) this.#emitSave(undo, this.#current());
      this.#render('arrange');
    });

    on('.tile__move', 'click', (e) => {
      const key = (e.currentTarget as HTMLElement).dataset.key!;
      const [dir, repo] = [key.slice(0, key.indexOf(':')), key.slice(key.indexOf(':') + 1)];
      const at = this.#draft.findIndex((a) => a.repo === repo);
      const to = dir === 'up' ? at - 1 : at + 1;
      this.#move(repo, to);
      // At either end that button is disabled, so focus moves to the one that still works.
      const atEnd = to === 0 || to === this.#draft.length - 1;
      this.#render(atEnd ? `${to === 0 ? 'down' : 'up'}:${repo}` : key);
    });
    on('.tile__toggle', 'click', (e) => {
      const key = (e.currentTarget as HTMLElement).dataset.key!;
      const repo = key.slice('toggle:'.length);
      const app = this.#draft.find((a) => a.repo === repo);
      if (this.#draftHidden.delete(repo)) this.#announce = `${app?.name} shown.`;
      else {
        this.#draftHidden.add(repo);
        this.#announce = `${app?.name} hidden. It stays under More apps.`;
      }
      this.#render(key);
    });

    // Dragging is extra, for a mouse or trackpad; the buttons do the same with touch and keyboard.
    if (this.#arranging && matchMedia('(pointer: fine)').matches) {
      this.querySelectorAll<HTMLElement>('.tile--arrange').forEach((tile) => {
        const repo = tile.dataset.repo!;
        tile.draggable = true;
        tile.addEventListener('dragstart', (e) => {
          this.#dragging = repo;
          e.dataTransfer?.setData('text/plain', repo);
          if (e.dataTransfer) e.dataTransfer.effectAllowed = 'move';
          tile.dataset.dragging = '';
        });
        tile.addEventListener('dragend', () => {
          this.#dragging = undefined;
          this.#render();
        });
        tile.addEventListener('dragover', (e) => {
          if (!this.#dragging || this.#dragging === repo) return;
          e.preventDefault();
          tile.dataset.dropTarget = '';
        });
        tile.addEventListener('dragleave', () => delete tile.dataset.dropTarget);
        tile.addEventListener('drop', (e) => {
          e.preventDefault();
          const dragged = this.#dragging;
          this.#dragging = undefined;
          if (dragged) this.#move(dragged, this.#draft.findIndex((a) => a.repo === repo));
          this.#render();
        });
      });
    }
  }
}

customElements.define('hh-tiles', HhTiles);

declare global {
  interface HTMLElementTagNameMap {
    'hh-tiles': HhTiles;
  }
}
